# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2020-11-19 17:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webui', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoken',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 19, 9, 55, 19, 593142), null=True),
        ),
        migrations.AlterField(
            model_name='virulence',
            name='source',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='virulence',
            name='type',
            field=models.IntegerField(),
        ),
    ]
