# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2020-11-21 06:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webui', '0002_auto_20201119_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoken',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 20, 22, 58, 59, 665637), null=True),
        ),
    ]
