# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2020-11-23 21:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webui', '0003_auto_20201120_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoken',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 23, 13, 28, 17, 724540), null=True),
        ),
    ]
