# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2020-11-25 16:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webui', '0004_auto_20201123_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoken',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 25, 8, 38, 15, 845680), null=True),
        ),
    ]
