# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2021-04-22 15:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webui', '0005_auto_20201125_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoken',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 22, 8, 23, 51, 850683), null=True),
        ),
    ]
