# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2026-10-02 23:26


from django.db import migrations, models
import webui.models


class Migration(migrations.Migration):

    dependencies = [
        ('webui', '0006_auto_20210422_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoken',
            name='expires',
            field=models.DateTimeField(default=webui.models.default_token_expiry, null=True),
        ),
    ]
